### ISSUE TITLE
Reporting - Double counting transactions that went to wrong account

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#30]
Some transactions went to the incorrect PayPal account.

These were then logged correctly, but for some reason they are being double counted in our sales total report.

**Comment by CarlNelson** [comment]
Will link ticket transactions once I find them.

**Comment by CarlNelson** [comment]
[Ticket 249](https://register.lindyfocus.com/admin/ticket/ticket/249/)
[Ticket 269](https://register.lindyfocus.com/admin/ticket/ticket/269/)
[Ticket 259](https://register.lindyfocus.com/admin/ticket/ticket/259/)
[Ticket 265](https://register.lindyfocus.com/admin/ticket/ticket/265/)
[Ticket 268](https://register.lindyfocus.com/admin/ticket/ticket/268/)
[Ticket 272](https://register.lindyfocus.com/admin/ticket/ticket/272/)

**Comment by NicoleZuckerman** [comment]
@NorthIsUp it looks like there are two paypal ipns for each of these.
I.e. for 249, there are two ipn records, but they both have the same txn_id.  In slack, you said "it looks like she got them merged into the correct account" -- how did you know this? Did you also do anything manually? Do you think it's safe to delete one IPN for each of these records, since they appear to be duplicates?

**Comment by CarlNelson** [comment]
Needs an IPN filter for not-flagged in reporting

**Comment by NicoleZuckerman** [comment]
We already have the IPN filter for flagged transactions, but the IPNs that are duplicates were not, in fact, marked as flagged.
@CarlNelson just went in and marked them manually through the admin.
