### ISSUE TITLE
Self Check-In Experience

### ISSUE THREAD

**Issue by CarlNelson** [SugarPushCode/FocusOnLindy#54]
Create an experience to allow attendees to self serve check-in for the event so that they only need to pick up their arm band.

Must have a profile photo and be fully paid up.

Prototype: https://invis.io/PE8ST33SN

**Comment by NicoleZuckerman** [comment]
1) can the initial screen be just email content? There’s nothing on there that requires it be web, except for the “check in now” button— that button could direct someone to their OWN check-in link based on what we know about their ticket.  I think this page should also link to registration where they can finish getting additional addons.
2) What happens in the flow if you haven’t paid everything yet?
3) What happens if you don’t have a profile photo yet?
4) Need content for digital waiver
5) Note: We are currently conflating “checked in” with “waiver signed"

**Comment by CarlNelson** [comment]
Finish up flows for ^

**Comment by CarlNelson** [comment]
4) Yeah, will work Jaya to get that.
3) No profile photo flow - https://invis.io/5S8YRTCNM#/197202790_010_-_No_Picture_Email
2) Please pay first flow - https://invis.io/MN8YRTH8P#/197202787_006_-_Email_To_Attendee_Unpaid

**Comment by CarlNelson** [comment]
For people who haven't paid and don't have a photo, show them the pay us section first, then ask for a photo to be uploaded.

**Comment by NicoleZuckerman** [comment]
I've updated the photo stuff, started doing the pay first stuff, but probably need some refactoring of paypal code to make that stuff happen. Will work on it with Adam tomorrow.
In the meantime, if you don't have a photo uploaded on your profile yet in production, can you let me log in as you on my phone and see what the experience is like?

**Comment by CarlNelson** [comment]
Can do, I didn't upload a photo yet.

**Comment by CarlNelson** [comment]
To include base template to get more styling and urchin for free.

**Comment by NicoleZuckerman** [comment]
-paypal stuff should work for self check in.  For desk check in, will use square.
The core of this ticket is basically done-- needs a @CarlNelson facelift.

**Comment by CarlNelson** [comment]
Okay, I will assign to myself.
